# Generated by Django 2.1.5 on 2019-02-09 17:55

import bookmark.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=bookmark.fields.AutoSlugField(blank=True, editable=False, max_length=100, null=True, populate_from='name', unique=True),
        ),
    ]
