# Generated by Django 2.1.7 on 2019-04-13 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190209_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='link_check_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='link_check_result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
