# Generated by Django 2.2.10 on 2020-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20190413_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
