# Generated by Django 2.2.10 on 2020-03-07 15:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_tag_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
