# Generated by Django 3.2.15 on 2022-10-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_auto_20200307_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-create_date']},
        ),
    ]
