# Generated by Django 5.1.1 on 2024-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
