# Generated by Django 5.1.1 on 2024-09-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_title_alter_note_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('inprogress', 'In progress'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=15),
        ),
    ]
