# Generated by Django 5.1.3 on 2024-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='assistant_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
