# Generated by Django 5.1.7 on 2025-03-10 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_assistant_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='estimated_effort',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default=None, max_length=15),
        ),
        migrations.CreateModel(
            name='NoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('deferred', 'Deferred'), ('updated', 'Updated')], default=None, max_length=15)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
