# Generated by Django 5.1.7 on 2025-03-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
