# Generated by Django 5.1.7 on 2025-03-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_recurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default=None, max_length=10, null=True),
        ),
    ]
