# Generated by Django 5.1.7 on 2025-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_note_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('bookmark', 'Bookmark'), ('task', 'Task'), ('idea', 'Idea')], default='bookmark', max_length=15),
        ),
    ]
