# Generated by Django 5.1.7 on 2025-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_user_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='estimated_effort',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
