# Generated by Django 5.1.7 on 2025-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_fulltext_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='notehistory',
            name='action',
            field=models.CharField(choices=[('deferred', 'Deferred'), ('updated', 'Updated'), ('promoted', 'Promoted')], default=None, max_length=15),
        ),
    ]
