# Generated by Django 5.2.5 on 2025-09-09 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0026_note_update_date_alter_notesprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('tags', 'Tags'), ('search', 'Search')], default='tags', max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'ordering': ['name'],
            },
        ),
    ]
