# Generated by Django 5.2.5 on 2025-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_savedfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
