# Generated by Django 5.2.6 on 2025-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tags', models.JSONField()),
                ('suggested_tag', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('support', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tag Suggestion',
                'verbose_name_plural': 'Tag Suggestions',
            },
        ),
    ]
