# Generated by Django 5.2.6 on 2025-09-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0030_tagsuggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsuggestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='tagsuggestion',
            name='input_tags',
        ),
        migrations.CreateModel(
            name='TagSuggestionInputTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_tags', to='notes.tagsuggestion')),
            ],
        ),
    ]
