# Generated by Django 5.2.7 on 2025-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0032_savedfilter_order_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
