# Generated by Django 5.2.7 on 2025-10-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0033_notesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='label',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
