# Generated by Django 6.0.7 on 2026-08-27 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0038_alter_notesprofile_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="combinedsearch",
            options={"managed": False},
        ),
    ]
