# Generated by Django 6.0.7 on 2026-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0040_dedupe_notetag_duplicates"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notetag",
            constraint=models.UniqueConstraint(fields=("note", "tag"), name="unique_note_tag"),
        ),
    ]
