# Generated by Django 6.0.7 on 2026-08-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0045_link_check_email_notesconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="link_check_ignore_redirects",
            field=models.BooleanField(default=False),
        ),
    ]
