# Generated by Django 6.0.7 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0047_link_check_batch_size_notesconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="link_check_fail_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
