# Generated by Django 6.1.1 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0050_alter_notesprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="link_check_known_good",
            field=models.BooleanField(default=False),
        ),
    ]
